config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "records#index"
  resources :records

end

app/models/record.rb
class Record < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :records

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user_records

  def current_user_records
  	current_user.records
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController

	before_action :authenticate_user!

	def index
		@records = current_user_records
	end

	def new	
		@record = Record.new
	end

	def create
		@record = Record.new(record_params)
		@record.user_id = current_user.id
		if @record.save
			redirect_to records_path
		else
			render :new
		end

	end

	def edit
		@record = Record.find(params[:id])
	end

	def update
		@record = Record.find(params[:id])
		if @record.update(record_params)
			redirect_to records_path
		else
			render :edit
		end
	end

	def destroy
		@record = Record.find(params[:id])
		@record.destroy
		redirect_to records_path
	end

	private

	def record_params
		params.require(:record).permit(:description, :price)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
	def render_total_price
		@records =  current_user_records
		sum = 0
		@records.each do |e|
			sum = sum + e.price
		end
		sum
	end

	def render_online_user_count
		user_cont  =  User.count
	end
end

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">
    Copyright ©2015 Meony Record <br>
    Design by <a href="http://blog-fred.logdown.com" target=_new>Fred</a>
  </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">MoneyRecord</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user%>
          <li> <%= link_to("登入", new_user_session_path) %> </li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Hi!, <%= current_user.email %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li> <%= link_to("登出", destroy_user_session_path, method: :delete ) %> </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MoneyRecord</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">
<%= render "common/navbar" %>
<%= yield %>
</div>
<%= render "common/footer" %>

</body>
</html>

app/views/records/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <h1>更新每筆開銷</h1>

  <hr>
  <%= simple_form_for @record do |f| %>
    <div class="form-group">
      <%= f.input :description, input_html: { class: "form-control"} %>
      <%= f.input :price, input_html: { class: "form-control"} %>
    </div>
    <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submitting..." } %>
  <% end %>
</div>

app/views/records/index.html.erb
<div class="col-md-12">
  <div class="new_record">
    <%= link_to("New Record", new_record_path, class: "btn btn-primary pull-right") %>
  </div>
  <p>註冊用戶: <%= render_online_user_count %> 人</p>
  <table class="table table-hover">
    <thead>
      <tr>
        <td>#</td>
        <td>Description</td>
        <td>price</td>
      </tr>
    </thead>
    <tbody>
      <% @records.each do |record| %>
        <tr>
          <td>#</td>
          <td><%= link_to(record.description, record_path(record)) %></td>
          <td><%= record.price %></td>
          <td>
              <%= link_to("Edit", edit_record_path(record), class: "btn btn-sm btn-default")%>
              <%= link_to("Delete", record_path(record),    class: "btn btn-sm btn-default", 
                          method: :delete, data: { confirm: "Are you sure?" } )%>
          </td>
        </tr>
      <% end %>
    </tbody>
    <td>
      <td>Total</td>
      <td><%= render_total_price %></td>
    </td>
  </table>
</div>

app/views/records/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h1>新增每筆開銷</h1>

  <hr>
  <%= simple_form_for @record do |f| %>
    <div class="form-group">
      <%= f.input :description, input_html: { class: "form-control"} %>
      <%= f.input :price, input_html: { class: "form-control"} %>
    </div>

    <div class="row">
        <div class='col-sm-6'>
            <div class="form-group">
                <div class='input-group date' id='datetimepicker1'>
                    <input type='text' class="form-control" />
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            $(function () {
                $('#datetimepicker1').datetimepicker();
            });
        </script>
    </div>

    <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submitting..." } %>
  <% end %>
</div>